name: Docker CI

on:
  push:
    branches: [ master ]

jobs:

  build-push-images:
    name: Budowa obrazów dla różnych architektur
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Tag names
      id: meta
      uses: docker/metadata-action@v3
      with:
        tags: |
          event=push,type=sha,format=short
          event=tag,type=ref
      
    - name: Set up Qemu
      uses: docker/setup-qemu-action@v1
      
    - name: Buildx set-up
      id: buildx
      uses: docker/setup-buildx-action@v1
      
   # - name: Login to DockerHub
   #   uses: docker/login-action@v1
   #   with: 
   #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
   #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
   # - name: Build image
   #   uses: docker/build-push-action@v2
   #   with: 
   #     context: .
   #     file: ./Dockerfile
   #     platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
   #     push: true
   #     tags: michalnurz/labox:gittchdocker
   #     cache-from: type=local,src=/tmp/.buildx-cache
   #     cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        
    - name: Push image to ghcr
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./Dockerfile
        platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha, scope=interop-sequencer
        cache-to: type=gha, scope=interop-sequencer, mode=max
        
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    
    - name: Image digest
      run: echo $ {{ steps.docker_build.outputs.digest }}
