name: Docker CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
    paths-ignore:
      - '**.md'
      
jobs:

  build-push-images:
    name: Budowa obrazów dla różnych architektur
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Qemu
      uses: docker/setup-qemu-action@v1
      
    - name: Buildx set-up
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
        flavor: latest=true
      
   # - name: Login to DockerHub
   #   uses: docker/login-action@v1
   #   with: 
   #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
   #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
   # - name: Build image
   #   uses: docker/build-push-action@v2
   #   with: 
   #     context: .
   #     file: ./Dockerfile
   #     platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
   #     push: true
   #     tags: michalnurz/labox:gittchdocker
   #     cache-from: type=local,src=/tmp/.buildx-cache
   #     cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    
    - if: startsWith(github.ref, 'refs/heads/master')
      run: echo "TAG=latest" >> $GITHUB_ENV
    - if: startsWith(github.ref, 'refs/tags')
      run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
        push: true
        tags: ghcr.io/remqes/cloudstech-test-app:latest
    
    - name: Image digest
      run: echo $ {{ steps.docker_build.outputs.digest }}
